version: '3'
services:
    backend_blue:
        build:
            context: .
            dockerfile: ${DOCKERFILE}
        image: backend:blue
        container_name: backend-blue
        ports:
            - '3005:3005'
        networks:
            - wedlock-network
        restart: always
        env_file:
            - .env
        environment:
            - TZ=Asia/Kolkata
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:3005/test"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 10s
networks:
  wedlock-network:
    external: true
